name: 🤖 Autonomous Daily Logs Bot

on:
  schedule:
    # Runs daily at 00:00 UTC (completely independent)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows manual trigger for testing

jobs:
  autonomous-daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: 🤖 Bot Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🐍 Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 🔧 Configure Git Bot Identity
      run: |
        git config --global user.name "blogecoin"
        git config --global user.email "blogecoin@github-bot.ai"

    - name: 📊 Generate Autonomous Log Entry
      run: |
        python autonomous_bot.py

    - name: 🤖 Autonomous Commit & Push
      run: |
        git add .
        if ! git diff --staged --quiet; then
          TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
          git commit -m "🤖 autonomous update $TIMESTAMP"
          git push origin main
          echo "✅ Autonomous commit completed at $(date -u)"
        else
          echo "ℹ️ No changes to commit"
        fi

    - name: 📋 Bot Status Report
      run: |
        echo "🤖 Bot Status: Active"
        echo "📅 Last Run: $(date -u)"
        echo "🔗 Repository: ${{ github.repository }}"
        echo "✅ Autonomous operation successful"