name: Simple Test Bot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  simple-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create log
      run: |
        echo "Auto update at $(date -u)" >> simple_log.txt

    - name: Commit and push
      run: |
        git config --global user.name "blogecoin"
        git config --global user.email "blogecoin@users.noreply.github.com"
        git add simple_log.txt
        git commit -m "auto update $(date -u +%Y%m%d_%H%M%S)" || echo "Nothing to commit"
        git push || echo "Push failed"